# Değişken Dönüşümleri

In [22]:
import numpy as np
import seaborn as sns
import pandas as pd
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# 0-1 DÖNÜŞÜMÜ

In [23]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [24]:
lbe.fit_transform(df["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [25]:
    df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [26]:
df["yeni_sex"] = lbe.fit_transform(df["sex"])

In [27]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex
0         16.99  1.01  Female     No   Sun  Dinner     2         0
1         10.34  1.66    Male     No   Sun  Dinner     3         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1
242       17.82  1.75    Male     No   Sat  Dinner     2         1
243       18.78  3.00  Female     No  Thur  Dinner     2         0

[244 rows x 8 columns]

# "1 ve DİĞERLERİ(0)"DÖNÜŞÜMÜ

In [28]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0

In [29]:
#Sun değeri varsa 1 de, diğerleri varsa 0 de.
df["yeni_day"]=np.where(df["day"].str.contains("Sun"),1,0)

In [30]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day
0         16.99  1.01  Female     No   Sun  Dinner     2         0         1
1         10.34  1.66    Male     No   Sun  Dinner     3         1         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0         1
..          ...   ...     ...    ...   ...     ...   ...       ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0

[244 rows x 9 columns]

# ÇOK SINIFLI DÖNÜŞÜM

In [31]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [32]:
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

# One-Hot Dönüşümü ve Dummy Değişken Tuzağı

In [33]:
df_one_hot=pd.get_dummies(df,columns = ["sex"],prefix=["sex"])

In [34]:
df_one_hot.head()

total_bill   tip smoker  day    time  size  yeni_sex  yeni_day  sex_Male  \
0       16.99  1.01     No  Sun  Dinner     2         0         1         0   
1       10.34  1.66     No  Sun  Dinner     3         1         1         1   
2       21.01  3.50     No  Sun  Dinner     3         1         1         1   
3       23.68  3.31     No  Sun  Dinner     2         1         1         1   
4       24.59  3.61     No  Sun  Dinner     4         0         1         0   

   sex_Female  
0           1  
1           0  
2           0  
3           0  
4           1

In [35]:
pd.get_dummies(df,columns = ["day"],prefix=["day"]).head()

total_bill   tip     sex smoker    time  size  yeni_sex  yeni_day  \
0       16.99  1.01  Female     No  Dinner     2         0         1   
1       10.34  1.66    Male     No  Dinner     3         1         1   
2       21.01  3.50    Male     No  Dinner     3         1         1   
3       23.68  3.31    Male     No  Dinner     2         1         1   
4       24.59  3.61  Female     No  Dinner     4         0         1   

   day_Thur  day_Fri  day_Sat  day_Sun  
0         0        0        0        1  
1         0        0        0        1  
2         0        0        0        1  
3         0        0        0        1  
4         0        0        0        1

# Sürekli Değişkeni Kategorik Değişkene Çevirmek

In [36]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  yeni_day
0       16.99  1.01  Female     No  Sun  Dinner     2         0         1
1       10.34  1.66    Male     No  Sun  Dinner     3         1         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0         1

In [56]:
dff=df.select_dtypes(include=["float64","int64"])

In [57]:
from sklearn.preprocessing import KBinsDiscretizer

est = KBinsDiscretizer(n_bins=[3, 2, 2], encode="ordinal", strategy="quantile").fit(dff)


In [58]:
est.transform(dff)[0:10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

# Değişkeni İndexe, İndexi Değişkene Çevirme

In [59]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day
0         16.99  1.01  Female     No   Sun  Dinner     2         0         1
1         10.34  1.66    Male     No   Sun  Dinner     3         1         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0         1
..          ...   ...     ...    ...   ...     ...   ...       ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0

[244 rows x 9 columns]

In [60]:
df["yeni_degisken"] = df.index

In [61]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day  \
0         16.99  1.01  Female     No   Sun  Dinner     2         0         1   
1         10.34  1.66    Male     No   Sun  Dinner     3         1         1   
2         21.01  3.50    Male     No   Sun  Dinner     3         1         1   
3         23.68  3.31    Male     No   Sun  Dinner     2         1         1   
4         24.59  3.61  Female     No   Sun  Dinner     4         0         1   
..          ...   ...     ...    ...   ...     ...   ...       ...       ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0   
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0   
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0   

     yeni_degisken  
0                0  
1                1  
2                2  
3                3  
4                4  
..             ...  
239            239  
240            240  
241            241  
242            242  
243            243  

[244 rows x 10 columns]

In [62]:
df["yeni_degisken"]=df["yeni_degisken"]+10

In [63]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day  \
0         16.99  1.01  Female     No   Sun  Dinner     2         0         1   
1         10.34  1.66    Male     No   Sun  Dinner     3         1         1   
2         21.01  3.50    Male     No   Sun  Dinner     3         1         1   
3         23.68  3.31    Male     No   Sun  Dinner     2         1         1   
4         24.59  3.61  Female     No   Sun  Dinner     4         0         1   
..          ...   ...     ...    ...   ...     ...   ...       ...       ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0   
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0   
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0   

     yeni_degisken  
0               10  
1               11  
2               12  
3               13  
4               14  
..             ...  
239            249  
240            250  
241            251  
242            252  
243            253  

[244 rows x 10 columns]

In [64]:
df.index = df["yeni_degisken"]

In [65]:
df.index

Int64Index([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,
            ...
            244, 245, 246, 247, 248, 249, 250, 251, 252, 253],
           dtype='int64', name='yeni_degisken', length=244)